title:              Tecnologia lliure per a un món lliure
tagline:            on GitHub Pages
description:        Content-focused template for a blog hosted on GitHub Pages.
url:                http://didacrios.github.io

author:
  name:             Dídac Ríos
  url:              https://twitter.com/didacrios
  email:            didac.rios@protonmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-midnight
