title:              Tecnologia lliure per a un món lliure
tagline:            ""
description:        "Un bloc en català dedicat a compartir coneixements, experiències i reflexions sobre tecnologia, desenvolupament de programari i bones pràctiques per construir un món digital més lliure i sostenible."
url:                http://didacrios.cat
locale:             ca_ES
timezone:           "Europe/Madrid"

author:
  name:             Dídac Ríos
  url:              https://x.com/didacrios
  email:            didac.rios@proton.me

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           3
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: jekyll-theme-midnight
